name: Comment on native files changed

on:
  pull_request:
    branches: 
      - 'main'
    paths:
      - '**.kt'
      - '**.java'
      - '**.swift'
      - '**.mm'
      - '**.h'
      - 'AndroidManifest.xml'
      - 'project.pbxproj'
      - 'package.json'

jobs:
  commentOnNativeFilesChanged:
    name: Create comment
    runs-on: ubuntu-latest
    steps: 
      - name: Comment
        run: |
          gh pr comment ${{ github.event.number }} --body \
          ":warning: This PR may change native code. It may cause problems in Hybrid App. Please notify people working on it to review those changes. :warning:"
        env:
          GITHUB_TOKEN: ${{ github.token }}
